"""Nessus API key storage and management.

Provides secure persistent storage for Nessus API keys at ~/.config/enso/nessus_keys.
Keys are stored with 600 permissions and loaded automatically when NessusConfig is created.
"""

import os
import stat
from pathlib import Path
from typing import NamedTuple


class NessusKeys(NamedTuple):
    """Container for Nessus API credentials."""
    access_key: str
    secret_key: str


# Default location for key file
NESSUS_KEY_FILE = Path.home() / ".config" / "enso" / "nessus_keys"


def get_key_file_path() -> Path:
    """Get the path to the Nessus key file.
    
    Can be overridden via ENSO_NESSUS_KEY_FILE environment variable.
    """
    return Path(os.environ.get("ENSO_NESSUS_KEY_FILE", str(NESSUS_KEY_FILE)))


def _check_legacy_key_file() -> None:
    """Check for legacy ~/.config/anet/nessus_keys and warn if found."""
    import sys
    legacy_path = Path.home() / ".config" / "anet" / "nessus_keys"
    if legacy_path.exists():
        print(
            f"WARNING: Found legacy key file at {legacy_path}\n"
            f"  Please move it to {NESSUS_KEY_FILE}\n"
            f"  Run: mkdir -p {NESSUS_KEY_FILE.parent} && "
            f"mv {legacy_path} {NESSUS_KEY_FILE}",
            file=sys.stderr,
        )


def load_nessus_keys() -> NessusKeys | None:
    """Load Nessus API keys from the secure key file.

    Returns:
        NessusKeys if file exists and is valid, None otherwise
    """
    key_file = get_key_file_path()

    if not key_file.exists():
        _check_legacy_key_file()
        return None
    
    try:
        content = key_file.read_text().strip()
        lines = content.split("\n")
        
        access_key = None
        secret_key = None
        
        for line in lines:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            
            if "=" in line:
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                
                if key == "access_key":
                    access_key = value
                elif key == "secret_key":
                    secret_key = value
        
        if access_key and secret_key:
            return NessusKeys(access_key=access_key, secret_key=secret_key)
        
        return None
        
    except (IOError, ValueError):
        return None


def save_nessus_keys(access_key: str, secret_key: str) -> Path:
    """Save Nessus API keys to the secure key file.
    
    Creates the directory and file with proper 600 permissions.
    
    Args:
        access_key: Nessus API access key
        secret_key: Nessus API secret key
        
    Returns:
        Path to the key file
    """
    key_file = get_key_file_path()
    
    # Create directory with 700 permissions
    key_file.parent.mkdir(parents=True, exist_ok=True)
    os.chmod(key_file.parent, stat.S_IRWXU)  # 700
    
    # Write key file
    content = f"""# ENSO Nessus API Keys
# Generated by: enso nessus setup
# This file should have 600 permissions (owner read/write only)

access_key = {access_key}
secret_key = {secret_key}
"""
    
    key_file.write_text(content)
    
    # Set 600 permissions (owner read/write only)
    os.chmod(key_file, stat.S_IRUSR | stat.S_IWUSR)  # 600
    
    return key_file


def delete_nessus_keys() -> bool:
    """Delete stored Nessus API keys.
    
    Returns:
        True if keys were deleted, False if no keys existed
    """
    key_file = get_key_file_path()
    
    if key_file.exists():
        key_file.unlink()
        return True
    
    return False


def check_key_file_permissions() -> tuple[bool, str]:
    """Check if key file has secure permissions.
    
    Returns:
        Tuple of (is_secure, message)
    """
    key_file = get_key_file_path()
    
    if not key_file.exists():
        return False, "Key file does not exist"
    
    file_stat = key_file.stat()
    mode = file_stat.st_mode
    
    # Check that only owner has read/write
    other_perms = mode & (stat.S_IRWXG | stat.S_IRWXO)
    
    if other_perms == 0:
        return True, f"Key file has correct permissions (600)"
    else:
        perms = oct(mode)[-3:]
        return False, f"Key file has insecure permissions ({perms}), should be 600"
